version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=rootuser
  db-gui:
    image: sosedoff/pgweb
    container_name: 'pgweb'
    ports:
      - '8081:8081'
    depends_on:
      - db

volumes:
  db-store:
